# Generated by Django 4.2.5 on 2023-09-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=50)),
                ('u_email', models.CharField(max_length=50, null=True)),
                ('cat_name', models.CharField(max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
