# Generated by Django 4.1.7 on 2023-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("Q_answer", models.CharField(max_length=30)),
                ("dislike", models.IntegerField()),
                ("like", models.IntegerField()),
                ("u_email", models.CharField(max_length=100, null=True)),
                ("Q_ID", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
