# Generated by Django 4.2.5 on 2023-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OurUser",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, null=True)),
                ("email", models.CharField(max_length=50, null=True)),
                ("password", models.TextField(null=True)),
                ("Bio", models.TextField(null=True)),
                ("Num_of_followers", models.IntegerField(null=True)),
                ("Num_of_following", models.IntegerField(null=True)),
                ("user", models.CharField(max_length=100, null=True)),
                ("img", models.ImageField(null=True, upload_to="images/")),
                ("phone_No", models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
